### ISSUE TITLE
Improve workflows with thread locking

### ISSUE THREAD

**Issue by Jeredian** [PrintMakerLab/draft-repository#26]
### Description
We need to add new workflow to lock thread after issue/pr was closed

* Use attached example
* add schedule
* add permissions
* add concurrency
* instead of secrets.GITHUB_TOKEN use token generation (see other workflows)
* Keep comment about locking
   * for issues
   * for prs 

#### Example
```
    runs-on: ubuntu-latest
    steps:
      - name: Lock Outdated Threads
        uses: dessant/lock-threads@v5.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          process-only: 'issues, prs'
          issue-inactive-days: 60
          add-issue-labels: "status: outdated"
          pr-inactive-days: 60
          add-pr-labels: "status: outdated"
```

### Refs: https://github.com/dessant/lock-threads
